### ISSUE TITLE
Calling CheckNetFramework more then once

### ISSUE THREAD

**Issue by inventti-pedro** [ProjectHuman/NsisDotNetChecker#16]
I'm trying to call the plugin twice, example:

${If} {isXP}
!insertmacro CheckNetFramework 40Client
${ElseIf}
!insertmacro CheckNetFramework 45
${EndIf}

The makensis are pointing to a duplicate global variable error. 

I've tried to put the script logic in a Function, but the error now is that the call DotNetChecker::IsDotNet452Installed (yes, fixed) throws a invalid command.

There is a right way for doing it? I'm not quite familiarized with the scripting stuff.

**Comment by bveenvliet** [comment]
You could !include the nsh twice with a different name.

!include "DotNetChecker.nsh" !include "DotNetChecker2.nsh"
${If} ${AtLeastWinXP}
!insertmacro CheckNetFramework 40Full
${Else}
//MessageBox etc
Abort
${EndIf}

${If} ${AtLeastWinVista}
!insertmacro CheckNetFramework2 45
${Else}
//MessageBox etc
Abort
${EndIf}


On Fri, Jun 12, 2015 at 8:00 AM, Pedro <notifications@github.com> wrote:

> I'm trying to call the plugin twice, example:
>
> ${If} {isXP}
> !insertmacro CheckNetFramework 40Client
> ${ElseIf}
> !insertmacro CheckNetFramework 45
> ${EndIf}
>
> The makensis are pointing to a duplicate global variable error.
>
> I've tried to put the script logic in a Function, but the error now is
> that the call DotNetChecker::IsDotNet40ClientInstalled (yes, fixed) throws
> a invalid command.
>
> There is a right way for doing it? I'm not quite familiarized with the
> scripting stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectHuman/NsisDotNetChecker/issues/16>.
>



-- 

Later,
Brad

**Comment by inventti-pedro** [comment]
Nice! Thanks!
